// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB43PTlED7r8QxNw2tOjqoi6vJZ_6HtUIU',
    appId: '1:1032816845988:web:63eebe387503e93b1ef231',
    messagingSenderId: '1032816845988',
    projectId: 'todomvc-copy',
    authDomain: 'todomvc-copy.firebaseapp.com',
    storageBucket: 'todomvc-copy.appspot.com',
    measurementId: 'G-3CJJ86SBTB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgZRo82Ug64OoMpiV_xkvrRNH1IYOym_o',
    appId: '1:1032816845988:android:51a278e0e6ad113c1ef231',
    messagingSenderId: '1032816845988',
    projectId: 'todomvc-copy',
    storageBucket: 'todomvc-copy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB6P6mOvPW7AWsRgggEbQ3A2ME9D4JrtE',
    appId: '1:1032816845988:ios:fbdda0a9374230ef1ef231',
    messagingSenderId: '1032816845988',
    projectId: 'todomvc-copy',
    storageBucket: 'todomvc-copy.appspot.com',
    iosBundleId: 'com.example.copyTodoMvc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB6P6mOvPW7AWsRgggEbQ3A2ME9D4JrtE',
    appId: '1:1032816845988:ios:fbdda0a9374230ef1ef231',
    messagingSenderId: '1032816845988',
    projectId: 'todomvc-copy',
    storageBucket: 'todomvc-copy.appspot.com',
    iosBundleId: 'com.example.copyTodoMvc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB43PTlED7r8QxNw2tOjqoi6vJZ_6HtUIU',
    appId: '1:1032816845988:web:303d33d7da26eab51ef231',
    messagingSenderId: '1032816845988',
    projectId: 'todomvc-copy',
    authDomain: 'todomvc-copy.firebaseapp.com',
    storageBucket: 'todomvc-copy.appspot.com',
    measurementId: 'G-H52KBVGMZZ',
  );

}